name: terraform || azure-resources || deployment

run-name: run-by user-${{ github.actor }} from branch-${{ github.ref_name }} with run-id-${{ github.run_id }} with workflow#${{ github.run_number }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

env:
  working-directory: ./terraform

jobs:
  terraform-security-scan:
    name: Terraform Security Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Tflint
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: latest

      - name: Tflint Scan
        id: tflint
        run: tflint init && tflint
        working-directory: ${{ env.working-directory }}
        continue-on-error: true

      - name: Tfsec Scan
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: ${{ env.working-directory }}
          version: latest
          additional_args: --tfvars-file=${{ env.working-directory }}/terraform.tfvars
          soft_fail: true
